# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0005_auto_20161117_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='registration_id',
            field=models.CharField(max_length=200, verbose_name='Registration ID'),
        ),
    ]
